### ISSUE TITLE
Get-AzWvdHostPool call has incorrect parameters

### ISSUE THREAD

**Issue by gcmlpfaltaher** [tsrob50/WVD-Public#1]
https://github.com/tsrob50/WVD-Public/blob/78a94e1b0e9c31b0e87afccd01885fbd9b190c6f/WVDARM_ScaleHostPoolVMs.ps1#L150

Ran into this today in a test environment, and I received the following error: 
ERROR: Error getting host pool details: Cannot bind argument to parameter 'SubscriptionId' because it is null.Exception             :Type    : Microsoft.PowerShell.Commands.WriteErrorExceptionMessage : Error getting host pool details: Cannot bind argument to parameter 'SubscriptionId' because it is null.

Where it failed at was: $hostPool = Get-AzWvdHostPool -ResourceGroupName $hostPoolRg -HostPoolName $hostPoolName

Looking at the cmdlet documentation, https://docs.microsoft.com/en-us/powershell/module/az.desktopvirtualization/get-azwvdhostpool?view=azps-5.0.0, Get-AzWvdHostPool's parameters don't include HostPool name, but instead, Name.

Updated the call locally to instead be:
$hostPool = Get-AzWvdHostPool -ResourceGroupName $hostPoolRg -Name $hostPoolName

**Comment by tsrob50** [comment]
Thanks for submitting this.  That looks correct, the parameter is Name, not HostPoolName.  I suspect that was left over from the original script version that used the get-rdesessionhost command. Odd that it worked for me, must be an alias in the version I’m using. I updated the line and it tested good.

**Comment by virennegi1** [comment]
> https://github.com/tsrob50/WVD-Public/blob/78a94e1b0e9c31b0e87afccd01885fbd9b190c6f/WVDARM_ScaleHostPoolVMs.ps1#L150
> 
> Ran into this today in a test environment, and I received the following error: ERROR: Error getting host pool details: Cannot bind argument to parameter 'SubscriptionId' because it is null.Exception :Type : Microsoft.PowerShell.Commands.WriteErrorExceptionMessage : Error getting host pool details: Cannot bind argument to parameter 'SubscriptionId' because it is null.
> 
> Where it failed at was: $hostPool = Get-AzWvdHostPool -ResourceGroupName $hostPoolRg -HostPoolName $hostPoolName
> 
> Looking at the cmdlet documentation, https://docs.microsoft.com/en-us/powershell/module/az.desktopvirtualization/get-azwvdhostpool?view=azps-5.0.0, Get-AzWvdHostPool's parameters don't include HostPool name, but instead, Name.
> 
> Updated the call locally to instead be: $hostPool = Get-AzWvdHostPool -ResourceGroupName $hostPoolRg -Name $hostPoolName

Hi ..

I am also receiving same type of error

**Comment by virennegi1** [comment]
If anyone has any resolution, please provide me that?

**Comment by virennegi1** [comment]
I will be very grateful to you

**Comment by tsrob50** [comment]
I see that line 162 (was 150) in the WVDARM_ScaleHostPoolVM.ps1 script wasn't updated.  I'll test and update that.

The error message "ERROR: Error getting a list of user sessions: Cannot bind argument to parameter 'SubscriptionId' because it is null.Exception" is not from the WVDARM_ScaleHostPoolVM.ps1 script.  That message comes from the StopSH-MultiHostPols.ps1 script.  Is that the script you are having problems with? That script doesn't use the get-azwvdhostpool command.
